# Generated by Django 5.0.6 on 2024-09-03 23:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('other_category', models.ForeignKey(db_column='category_id1', max_length=45, on_delete=django.db.models.deletion.CASCADE, related_name='category_id1', to='omsanatanaapp.category')),
            ],
            options={
                'db_table': 'sub_category',
            },
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('pdf_location', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('category_id', models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='omsanatanaapp.category')),
                ('news_sub_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_sub_category_id', to='omsanatanaapp.subcategory')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
