# Generated by Django 5.0.6 on 2024-09-03 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsanatanaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='book',
            name='pdf_location',
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.CreateModel(
            name='BookPDF',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_location', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='omsanatanaapp.book')),
            ],
            options={
                'db_table': 'bookpdf',
                'managed': True,
            },
        ),
    ]
