# Generated by Django 5.0.6 on 2024-09-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsanatanaapp', '0003_alter_book_options_alter_bookpdf_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_location',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.DeleteModel(
            name='BookPDF',
        ),
    ]
