# Generated by Django 5.0.6 on 2024-09-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsanatanaapp', '0004_book_pdf_location_delete_bookpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
