# Generated by Django 5.0.6 on 2024-09-03 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omsanatanaapp', '0006_pdf_remove_book_pdf_location_book_pdf_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='omsanatanaapp.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='news_sub_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='omsanatanaapp.subcategory'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
